### PR TITLE
serviceAPI is used for all Requests

### PR DESCRIPTION
**Pull request by Rechi**
Now the serviceAPI is used to get all informations, but the parsing of the website is still the fallback, if the API isn't available.

### CODE REVIEW

**Comment by s0faking** [comment]
wow...very nice @Rechi. i've created a devel branch for the addon because i found a few things that didn't work(for example: Sendungen->ECO). can you add the pull request to the dev branch and delete it on the master branch?

**Comment by Rechi** [comment]
moved PR to #11 
Sendungen -> €co is working in my case.

**Comment by s0faking** [comment]
The Problem with Eco seems to be the setSubtitles function. setSubtitles needs to be called on the player object. With Kodi(Helix) the error doesn't seem to stop the script execution but on gotham i get an exception. Are the subtitles working on your xbmc installation? also i saw that the video quality sucks. Looks like only Q4A Video are available with the serviceAPI. maybe we should get the video detail page with the htmlparser after all and only parse the directory listings with the service api.

**Comment by Rechi** [comment]
The subtitles are working on Kodi 14.0, 14.1 and the actual nightlies. There should be a check if the version is greater or even 14 for setting the subtitles.
I will check the problem with the quality as soon as possible.

**Pull request closed without merging**
