### PR TITLE
Fix basic auth for ServiceAPI

### LINKED ISSUE #109: Service API: 401 Unauthorized
Seems like they've disabled the old API credentials?

HTML Scraper works though…

### PR DESCRIPTION
**Pull request by alexrashed**
Hi there!

Thanks for the awesome plugin! This PR updates the basic auth header value with new base64 encoded credentials.

Fixes #109

### CODE REVIEW

**Comment by killerbees19** [comment]
Thank you, works like a charm! :-)

**Comment by s0faking** [comment]
nice one, thx. how did you pull it off?

**Comment by alexrashed** [comment]
The creds are contained in the strings of the APK of the TVThek Android app.

**Comment by s0faking** [comment]
well thats not very safe ;) thanks for finding out.

**Comment by alexrashed** [comment]
Actually, there isn't really a "safe" option. Since you don't need an account / registration to use the app, you need to ship the secret with your app package. You could obfuscate the string, but that would only make it harder - not impossible - to extract...

**Comment by s0faking** [comment]
ah, thanks for clearing that up. i wasn't aware of that.

**Pull request merged**
