### PR TITLE
serviceAPI: fix play all

### PR DESCRIPTION
**Pull request by Rechi**
without this change Kodi will get completely get stuck when trying to open `Play all`

### CODE REVIEW

**Comment by s0faking** [comment]
add this to the isengard branch. i've already made the change in the jarvis branch

**Comment by Rechi** [comment]
Why have you stared to create different branches for different versions?
If you continue submitting it to Gotham (as you have done before) it will be in all versions newer than Gotham automatically.
http://kodi.wiki/view/Submitting_Add-ons#Allowed_submissions

**Comment by s0faking** [comment]
well as i'm not really testing the addon on gotham anymore i decided to move to jarvis.  do you think it would be better to support an older kodi version than jarvis? 

 i have to submit the updates to the offical repo with git now, thats why i made a jarvis branch. last time i did this for the puls4 addon i had to make quite some changes so i kind of tried to fix everything before i make my first pull request.

**Comment by Rechi** [comment]
Don't know if you are aware of http://mirrors.kodi.tv/stats?downloadstats=2017&filter=plugin.video.orftvthek. There you can see how often the addon has been downloaded for a specific kodi/addon version.

I would prefer if you still support older versions. Just have done a quick test and it does work.

If you need some assistance for submitting it to the official repo, just tell me.

**Comment by s0faking** [comment]
> Don't know if you are aware of http://mirrors.kodi.tv/stats?downloadstats=2017&filter=plugin.video.orftvthek. There you can see how often the addon has been downloaded for a specific kodi/addon version.

wow. i didnt know about a statistics site. thats good to know. well then i guess we stick to gotham. 

> If you need some assistance for submitting it to the official repo, just tell me.
thanks. appreciate it. i'll come back to you when i get the first feedback from the submission. they look really close now, went kinda easier with the mailinglist, but always good when people care if you ask me

**Pull request closed without merging**
