### PR TITLE
[fix][serviceapi] don't set isFolder = True for play all 

### PR DESCRIPTION
**Pull request by Rechi**

### CODE REVIEW

**Comment by s0faking** [comment]
thx @Rechi

**Comment by Rechi** [comment]
@s0faking can you push the update to the Kodi repo?

**Comment by s0faking** [comment]
already on it ;)

**Comment by HiassofT** [comment]
I'm still getting busy dialog related crashes (tested current head of master on todays Milhouse build), both with service api on and off.

Here's the kodi crashlog: http://ix.io/1coJ

Are some more addon fixes required or is this now Kodi's fault?

**Comment by Rechi** [comment]
Are you using the autopromp feature?

**Comment by HiassofT** [comment]
No, I've tested with plain defaults (autoplay prompt off and service api on/off)

Just retested with autoplay prompt on: With service api off I get the prompt and playing all from there is fine. Selecting no in the dialog and then using play all crashes kodi. With service api on no autoplay prompt dialog is show, and selecting play all from the list crashes kodi.

**Comment by s0faking** [comment]
i had to revert the changes. as @HiassofT stated this causes the current stable kodi version to crash when using the playall listitem.

**Comment by Rechi** [comment]
I only see a v18 crash report, can you share a v17 one?

**Pull request merged**
